version: '3.4'

services:
  jsonserverapp:
    image: jsonserverapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4000:4000
