version: '3.4'

services:
  chat-app-client:
    image: chat-app-client
    build:
      context: client
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000