version: '3.4'

services:
  mongo:
    image: mongo:latest
    ports: 
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  chat-app-server:
    image: chat-app-server
    build:
      context: server
      dockerfile: ./Dockerfile
    environment:
      MONGO_URI: mongodb://mongo:27017/chatApp
      PORT: 4000
      NODE_ENV: production
    ports:
      - 4000:4000

volumes:
  mongodb_data_container: